version: '3.4'

services:
  # customers service
  customers:
    image: customers
    build: 
      context: ./customers
      dockerfile: ./customers/Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8080:8080
      - 5003:5003
  # orders service
  orders:
    image: orders
    build: 
      context: ./orders
      dockerfile: ./orders/Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8081:8081
      - 5004:5004
  # gateway service (also the main service here..)
  gateway:
    image: gateway
    depends_on:
      - customers
      - orders
    build:
      context: ./gateway
      dockerfile: ./gateway/Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8082:8082
      - 5005:5005
