version: '3.4'

services:
  # customers service
  customers:
    image: customers
    container_name: customers
    build: 
      context: ./customers
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  # orders service
  orders:
    image: orders
    container_name: orders
    build: 
      context: ./orders
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
  # gateway service (also the main service here..)
  gateway:
    image: gateway
    container_name: microservice-example-gateway
    depends_on:
      - customers
      - orders
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    environment:
      - ORDERS_SERVICE_HOST=orders
      - ORDERS_SERVICE_PORT=8081
      - CUSTOMERS_SERVICE_HOST=customers
      - CUSTOMERS_SERVICE_PORT=8080
    ports:
      - 8082:8082
